### ISSUE TITLE
White Page error when used with MDTextField and SideDrawer

### ISSUE THREAD

**Issue by NavruzbekNoraliev** [nativescript-community/ui-material-components#229]
I get no error, no warning just blank white page, you can reproduce error by using above mentioned libraries in one module

**Comment by farfromrefug** [comment]
what sidedrawer? 
please what so you expect with such bug reports ?
first material text field works well on its on. second I suppose you are talking about nativescript ui sidedrawer which I don't maintain nor use. 
you need to find out where the issue comes from then post a detailed issue with repro sample and explanations on the correct repo.
