### ISSUE TITLE
Docs needs to be updated!

### ISSUE THREAD

**Issue by kefahB** [nativescript-community/ui-material-components#412]
Hi everyone,

It is really a shame that the docs of such a grate repos to be with a lot of error .. we spends ours in order to understand how it works!

Please, let's make it clear and intuitive for every body, we should think about new member to NS, if they hurt to the docs as it, they will go to other technology!!.

Tabs is a small example:

```xml

<Page xmlns:mdt="@nativescript-community/ui-material-tabs">
    <mdt:MDTabs selectedIndex="1"> <!-- HERE >> mdt:MDTabs -->
        <!-- The bottom tab UI is created via TabStrip (the containier) and TabStripItem (for each tab)-->
        <mdt:MDTabStrip>
            <mdt:MDTabStripItem> <!-- HERE >> mdt:MDTabStripItem-->
                <Label text="Home"></Label>
                <Image src="font://&#xf015;" class="fas"></Image>
            </MDTabStripItem> <!-- --------- HERE >> no mdt -->
            <mdt:MDTabStripItem>Item class="special">  <!-- LOK AT THIS!! -->
                <Label text="Account"></Label>
                <Image src="font://&#xf007;" class="fas"></Image>
            </MDTabStripItem>
            <mdt:MDTabStripItem>Item class="special">
                <Label text="Search"></Label>
                <Image src="font://&#xf00e;" class="fas"></Image>
            </MDTabStripItem>
        </MDTabStrip>

        <!-- The number of TabContentItem components should corespond to the number of TabStripItem components -->
        <mdt:MDTabContentItem>
            <GridLayout>
                <Label text="Home Page" class="h2 text-center"></Label>
            </GridLayout>
        </MDTabContentItem>
        <mdt:MDTabContentItem>
            <GridLayout>
                <Label text="Account Page" class="h2 text-center"></Label>
            </GridLayout>
        </MDTabContentItem>
        <mdt:MDTabContentItem>
            <GridLayout>
                <Label text="Search Page" class="h2 text-center"></Label>
            </GridLayout>
        </MDTabContentItem>
    </Tabs>  <!-- --------- HERE >> no mdt and no MDTabs  -->
</Page>
```

@farfromrefug @NathanWalker

**Comment by farfromrefug** [comment]
@kefahB i can understand tour frustration. But i need you to understand that those are community project managed by people on their free time. No one is paying me others to maintain this. 
You might have lost time (which I don't think are hours) I spends hours a week maintaining this, answering people and ensuring this works best for you. 
You are welcome to create PRs for doc that would be a great help. 
Side note: docs are great I agree but as a user of other libs I always tend to look at demos and examples first. They are almost always more up to date than docs ( because devs like me use it to test).
And this repo is no different. The vue app will always be showih the most recent way of using any component.

I am sorry and sad you are not happy. Yet my answer will always be the same about doc. If you don't like it you are welcome to create a PR. It will help you, me and all.the community

**Comment by kefahB** [comment]
Dear @farfromrefug, 

Of course I know that everybody work freely and generously .. and please do understand that my post here is not because I am not happy or some think, you know may be When I facing an issue I do push a PR I my competence allow me to do so.

My post is purely to go forward with NS.

About the demo, look at the repo, when you navigate to the [demo snippets ](https://github.com/nativescript-community/ui-material-components/tree/master/demo-snippets) you do not found the demo for Nativescript Core!, yes you can say it almost the same but not always.

With all respect for those who git there times for this repo espcially for you dear friend
